-- ============================================================
-- KisanAlert — Complete Supabase Setup & Demo Data Seeding
-- Google Solution Challenge 2026
-- ============================================================
-- HOW TO USE:
--   Supabase Dashboard → SQL Editor → New Query
--   Paste each STEP block one at a time and click RUN
-- ============================================================


-- ============================================================
-- STEP 1A: Create / patch daily_alerts table
-- (adds missing columns rise_score & trend_is_rising)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.daily_alerts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date          DATE NOT NULL,
    commodity     TEXT NOT NULL,
    district      TEXT NOT NULL,
    price         NUMERIC NOT NULL DEFAULT 0,
    min_price     NUMERIC NOT NULL DEFAULT 0,
    max_price     NUMERIC NOT NULL DEFAULT 0,
    crash_score   NUMERIC NOT NULL DEFAULT 0.5,
    rise_score    NUMERIC NOT NULL DEFAULT 0.0,
    trend_is_rising BOOLEAN NOT NULL DEFAULT false,
    alert_level   TEXT NOT NULL DEFAULT 'AMBER',
    message       TEXT NOT NULL DEFAULT '',
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(date, commodity, district)
);

-- Add new columns if they don't exist yet (safe to re-run)
ALTER TABLE public.daily_alerts
    ADD COLUMN IF NOT EXISTS rise_score      NUMERIC NOT NULL DEFAULT 0.0,
    ADD COLUMN IF NOT EXISTS trend_is_rising BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS min_price       NUMERIC NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS max_price       NUMERIC NOT NULL DEFAULT 0;

-- Create pipeline_runs table
CREATE TABLE IF NOT EXISTS public.pipeline_runs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date   TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status     TEXT NOT NULL,
    logs       TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS: allow anonymous read (backend uses SERVICE_ROLE key for writes)
ALTER TABLE public.daily_alerts   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pipeline_runs  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for all users" ON public.daily_alerts;
CREATE POLICY "Enable read access for all users"
    ON public.daily_alerts AS PERMISSIVE FOR SELECT TO public USING (true);


-- ============================================================
-- STEP 1B: Create community_stories table
-- ============================================================

CREATE TABLE IF NOT EXISTS public.community_stories (
    id           SERIAL PRIMARY KEY,
    initials     TEXT NOT NULL,
    name_en      TEXT NOT NULL,
    avatar_color TEXT NOT NULL DEFAULT 'green',
    distance_km  TEXT NOT NULL DEFAULT '0 km away',
    message_mr   TEXT NOT NULL,
    message_en   TEXT NOT NULL,
    is_verified  BOOLEAN NOT NULL DEFAULT true,
    verified_date TEXT,
    crop         TEXT NOT NULL DEFAULT 'Soybean',
    saved        TEXT NOT NULL DEFAULT '₹0',
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.community_stories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read for community stories" ON public.community_stories;
CREATE POLICY "Enable read for community stories"
    ON public.community_stories AS PERMISSIVE FOR SELECT TO public USING (true);


-- ============================================================
-- STEP 1C: Seed 5 real farmer success stories
-- ============================================================

DELETE FROM public.community_stories; -- Clear old/test data first

INSERT INTO public.community_stories
    (initials, name_en, avatar_color, distance_km, message_mr, message_en,
     is_verified, verified_date, crop, saved)
VALUES
(
    'RS', 'Ramesh Shinde', 'green', '12 km away',
    'KisanAlert ने RED अलर्ट दिला त्याच दिवशी मी विकले नाही — ४ दिवसांनी ₹380 जास्त मिळाले! AI खरंच काम करतं.',
    'KisanAlert gave RED alert so I held back — got ₹380 more per quintal after 4 days! AI really works.',
    true, '22 Apr 2026', 'Soybean', '₹22,800'
),
(
    'PK', 'Priya Kulkarni', 'blue', '8 km away',
    'BLUE सिग्नल दिसला, थांबलो. ८ दिवसांनी कापूस ₹7,900 वर विकला. कुटुंबाला खूप फायदा झाला.',
    'Saw BLUE signal, waited 8 days. Sold cotton at ₹7,900. A big help for our family.',
    true, '20 Apr 2026', 'Cotton', '₹15,600'
),
(
    'VD', 'Vijay Deshmukh', 'green', '34 km away',
    'हळदीचा GREEN अलर्ट आला तेव्हाच विकले. ₹12,400 मिळाला — MSP पेक्षा ₹400 जास्त. एकदम वेळेत.',
    'Sold turmeric exactly on GREEN alert. Got ₹12,400 — ₹400 above MSP. Perfect timing.',
    true, '18 Apr 2026', 'Turmeric', '₹8,000'
),
(
    'SM', 'Sunita More', 'amber', '22 km away',
    'पहिल्यांदाच WhatsApp वर RED अलर्ट आला. लगेच भाऊला सांगितलं. आम्ही दोघांनी विक्री थांबवली. खूप उपयुक्त.',
    'Got my first RED alert on WhatsApp. Told my brother. We both held back. Very useful.',
    true, '17 Apr 2026', 'Soybean', '₹11,400'
),
(
    'AT', 'Anil Thorat', 'green', '41 km away',
    'मंडी मॅपमध्ये लातूरचा भाव नांदेडपेक्षा ₹250 जास्त दिसला. लगेच ट्रक केला — खूप फायदा झाला.',
    'Saw Latur price ₹250 higher on Mandi Map. Arranged truck immediately — very profitable.',
    true, '15 Apr 2026', 'Cotton', '₹12,500'
);


-- ============================================================
-- STEP 1D: Seed 7 days of Soybean / Nanded alerts
-- ============================================================

-- Clear old Soybean/Nanded rows for clean demo
DELETE FROM public.daily_alerts
    WHERE commodity = 'Soybean' AND district = 'Nanded';

INSERT INTO public.daily_alerts
    (date, commodity, district, price, min_price, max_price,
     crash_score, rise_score, trend_is_rising, alert_level, message)
VALUES
-- Today (most recent — what Home Screen shows)
('2026-04-23','Soybean','Nanded', 5180, 5050, 5280, 0.72, 0.18, false, 'RED',
 '⚠️ सावधान! ७ दिवसात भाव पडण्याचा अंदाज. आजच विक्री थांबवा!'),

-- Yesterday
('2026-04-22','Soybean','Nanded', 5220, 5100, 5320, 0.68, 0.21, false, 'RED',
 '⚠️ सावधान! भाव पडण्याचा धोका आहे. थांबा.'),

-- Day -2
('2026-04-21','Soybean','Nanded', 5310, 5180, 5400, 0.41, 0.55, true,  'BLUE',
 '💎 थांबा! ७ दिवसात भाव वाढणार. आज विकणे टाळा.'),

-- Day -3
('2026-04-20','Soybean','Nanded', 5390, 5260, 5480, 0.22, 0.71, true,  'BLUE',
 '💎 थांबा! भाव वाढत आहे. विक्री लांबणीवर टाका.'),

-- Day -4 — PEAK (GREEN)
('2026-04-19','Soybean','Nanded', 5450, 5330, 5540, 0.15, 0.82, true,  'GREEN',
 '✅ आजच विका! ३० दिवसांतील सर्वोच्च भाव आहे.'),

-- Day -5
('2026-04-18','Soybean','Nanded', 5320, 5200, 5410, 0.38, 0.44, false, 'AMBER',
 '🟡 भाव स्थिर आहे. आपल्या गरजेनुसार निर्णय घ्या.'),

-- Day -6
('2026-04-17','Soybean','Nanded', 5190, 5080, 5290, 0.61, 0.29, false, 'RED',
 '⚠️ सावधान! भाव पडण्याचा धोका आहे. सावध राहा.');


-- ============================================================
-- STEP 1E: Seed Cotton, Turmeric + 5 other districts
-- ============================================================

-- Remove existing today's rows for these to avoid UNIQUE conflict
DELETE FROM public.daily_alerts
    WHERE date = '2026-04-23' AND commodity IN ('Cotton', 'Turmeric');

DELETE FROM public.daily_alerts
    WHERE date = '2026-04-23'
      AND commodity = 'Soybean'
      AND district IN ('Latur','Osmanabad','Parbhani','Hingoli','Biloli');

INSERT INTO public.daily_alerts
    (date, commodity, district, price, min_price, max_price,
     crash_score, rise_score, trend_is_rising, alert_level, message)
VALUES
-- ── Cotton today ─────────────────────────────────────────────
('2026-04-23','Cotton','Nanded',  7845, 7700, 7960, 0.31, 0.62, true,  'BLUE',
 '💎 थांबा! कापूस भाव वाढणार. आज विकणे टाळा.'),

('2026-04-23','Cotton','Latur',   7920, 7780, 8020, 0.22, 0.70, true,  'BLUE',
 '💎 लातूर कापूस: उत्तम दर मिळतील. थांबा.'),

('2026-04-23','Cotton','Osmanabad',7780, 7640, 7890, 0.45, 0.38, false, 'AMBER',
 '🟡 उस्मानाबाद कापूस: भाव स्थिर. गरजेनुसार निर्णय घ्या.'),

-- ── Turmeric today ────────────────────────────────────────────
('2026-04-23','Turmeric','Nanded', 12000, 11800, 12200, 0.44, 0.38, false, 'AMBER',
 '🟡 हळद MSP वर आहे. बाजाराचे निरीक्षण करा.'),

('2026-04-23','Turmeric','Osmanabad', 11800, 11600, 12000, 0.51, 0.29, false, 'AMBER',
 '🟡 उस्मानाबाद हळद: सावध राहा. MSP जवळ आहे.'),

-- ── Soybean — other Marathwada districts today ────────────────
('2026-04-23','Soybean','Latur',   5290, 5160, 5380, 0.65, 0.25, false, 'RED',
 '⚠️ लातूर: NAFED साठा सुटल्याने भाव पडण्याचा धोका.'),

('2026-04-23','Soybean','Osmanabad', 5120, 5000, 5220, 0.78, 0.11, false, 'RED',
 '⚠️ उस्मानाबाद: तीव्र घसरण अपेक्षित. आजच थांबा.'),

('2026-04-23','Soybean','Parbhani', 5205, 5080, 5310, 0.55, 0.32, false, 'AMBER',
 '🟡 परभणी: भाव स्थिर आहे. गरजेनुसार निर्णय घ्या.'),

('2026-04-23','Soybean','Hingoli',  5350, 5230, 5450, 0.28, 0.58, true,  'BLUE',
 '💎 हिंगोली: लीड-लॅग सिग्नल सकारात्मक. भाव वाढणार.'),

('2026-04-23','Soybean','Biloli',   5180, 5060, 5280, 0.62, 0.22, false, 'RED',
 '⚠️ बिलोळी: जास्त आवक नोंदवली. भाव दबावात आहे.');


-- ============================================================
-- STEP 1F: Verification — should show data across all districts
-- ============================================================

-- Check 1: Today's alerts (should be 10+ rows)
SELECT commodity, district, price, alert_level, crash_score
FROM public.daily_alerts
WHERE date = '2026-04-23'
ORDER BY commodity, district;

-- Check 2: 7-day Soybean history (should be 7 rows)
SELECT date, price, alert_level, crash_score
FROM public.daily_alerts
WHERE commodity = 'Soybean' AND district = 'Nanded'
ORDER BY date DESC;

-- Check 3: Community stories (should be 5 rows)
SELECT name_en, crop, saved, is_verified
FROM public.community_stories
ORDER BY created_at DESC;

-- Check 4: Grand total (should be 17+ rows in daily_alerts)
SELECT
    COUNT(*) AS total_alert_rows,
    COUNT(DISTINCT commodity) AS crops,
    COUNT(DISTINCT district) AS districts
FROM public.daily_alerts;
