// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Z69TxTVE5BHuc3LPFanNi8-Q-SnReXo',
    appId: '1:862035785988:web:3baf8dd51e43503b5cf851',
    messagingSenderId: '862035785988',
    projectId: 'campusbazaar-84af8',
    authDomain: 'campusbazaar-84af8.firebaseapp.com',
    storageBucket: 'campusbazaar-84af8.firebasestorage.app',
    measurementId: 'G-KXN13TYR5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1dTdq-dImRVZi1plulTQE4uA0evZcTQ0',
    appId: '1:862035785988:android:72b7920d4d53a7075cf851',
    messagingSenderId: '862035785988',
    projectId: 'campusbazaar-84af8',
    storageBucket: 'campusbazaar-84af8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4vmD7Xizd3iLW8HOwnDSus1NhLGgVNEE',
    appId: '1:862035785988:ios:806e39708c36f4af5cf851',
    messagingSenderId: '862035785988',
    projectId: 'campusbazaar-84af8',
    storageBucket: 'campusbazaar-84af8.firebasestorage.app',
    iosBundleId: 'com.example.kisanalertApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4vmD7Xizd3iLW8HOwnDSus1NhLGgVNEE',
    appId: '1:862035785988:ios:806e39708c36f4af5cf851',
    messagingSenderId: '862035785988',
    projectId: 'campusbazaar-84af8',
    storageBucket: 'campusbazaar-84af8.firebasestorage.app',
    iosBundleId: 'com.example.kisanalertApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2Z69TxTVE5BHuc3LPFanNi8-Q-SnReXo',
    appId: '1:862035785988:web:1e2f2c364094a2675cf851',
    messagingSenderId: '862035785988',
    projectId: 'campusbazaar-84af8',
    authDomain: 'campusbazaar-84af8.firebaseapp.com',
    storageBucket: 'campusbazaar-84af8.firebasestorage.app',
    measurementId: 'G-N54FE8Z5H2',
  );
}
