// lib/firebase_options.dart
// ⭐ Auto-generated by FlutterFire CLI: flutterfire configure
// Replace this stub with the real file after running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// The try/catch in main.dart means this compiles and runs
// even without a real google-services.json. FCM is disabled
// gracefully; the hourly timer fallback in startAutoRefresh() takes over.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  // ──────────────────────────────────────────────────────────────
  // REPLACE all values below with your real Firebase project config.
  // Get them from: Firebase Console → Project Settings → Your Apps
  // ──────────────────────────────────────────────────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:            'AIzaSyB1dTdq-dImRVZi1plulTQE4uA0evZcTQ0',
    appId:             '1:862035785988:android:72b7920d4d53a7075cf851',
    messagingSenderId: '862035785988',
    projectId:         'campusbazaar-84af8',
    storageBucket:     'campusbazaar-84af8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:            'REPLACE_WITH_YOUR_IOS_API_KEY',
    appId:             'REPLACE_WITH_YOUR_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId:         'REPLACE_WITH_YOUR_PROJECT_ID',
    storageBucket:     'REPLACE_WITH_YOUR_BUCKET.appspot.com',
    iosBundleId:       'com.example.kisanalertApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:            'REPLACE_WITH_YOUR_WEB_API_KEY',
    appId:             'REPLACE_WITH_YOUR_WEB_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId:         'REPLACE_WITH_YOUR_PROJECT_ID',
    authDomain:        'REPLACE_WITH_YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket:     'REPLACE_WITH_YOUR_BUCKET.appspot.com',
  );
}
