# -*- coding: utf-8 -*-
"""
KisanAlert Firebase Sync
Mirrors critical Supabase RED alerts into Firestore to trigger immediate Flutter App push notifications.
"""

import os
import logging
import firebase_admin
from firebase_admin import credentials, firestore

log = logging.getLogger(__name__)

# Note: The JSON path should be set in .env as FIREBASE_CREDENTIALS_PATH
# e.g., FIREBASE_CREDENTIALS_PATH=secret/firebase-admin.json

def get_firestore_client():
    """Initializes Firebase Admin SDK connection, or returns a mocked stub if missing."""
    if not firebase_admin._apps:
        cred_path = os.getenv("FIREBASE_CREDENTIALS_PATH")
        if cred_path and os.path.exists(cred_path):
            try:
                cred = credentials.Certificate(cred_path)
                firebase_admin.initialize_app(cred)
                log.info("Firebase Admin SDK initialized successfully.")
            except Exception as e:
                log.error(f"Failed to initialize Firebase Admin SDK: {e}")
                return None
        else:
            log.warning("Firebase credentials missing. Running Firebase Sync in STUB mode.")
            return None
    try:
        return firestore.client()
    except Exception:
        return None

def sync_alert_to_firestore(alert_data: dict) -> bool:
    """
    Takes an alert generated by KisanAlert and pushes it to Firestore collection 'live_alerts'.
    Returns True if successfully pushed, False otherwise (or if stubbed).
    """
    db = get_firestore_client()
    if not db:
        log.info(f"[STUB FIREBASE SYNC] Would push to Firestore: {alert_data['commodity']} - {alert_data['message']}")
        return False
        
    try:
        # Pushing the document to 'live_alerts' collection
        doc_ref = db.collection('live_alerts').document()
        doc_ref.set(alert_data)
        log.info(f"Successfully synced {alert_data['commodity']} alert to Firestore.")
        return True
    except Exception as e:
        log.error(f"Error syncing alert to Firestore: {e}")
        return False
