-- ==========================================
-- KisanAlert Backend Setup for Supabase
-- ==========================================
-- Run this script in the Supabase SQL Editor
-- ==========================================

-- 1. Create daily_alerts table
CREATE TABLE IF NOT EXISTS public.daily_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    commodity TEXT NOT NULL,
    district TEXT NOT NULL,
    price NUMERIC NOT NULL,
    crash_score NUMERIC NOT NULL,
    alert_level TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Ensure we only have one alert per commodity/district per day
    UNIQUE(date, commodity, district)
);

-- 2. Create pipeline_runs table
CREATE TABLE IF NOT EXISTS public.pipeline_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT NOT NULL,
    logs TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Row Level Security (RLS) Setup
-- Enable RLS
ALTER TABLE public.daily_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pipeline_runs ENABLE ROW LEVEL SECURITY;

-- Allow anyone to READ the alerts (for the mobile/web app)
CREATE POLICY "Enable read access for all users" ON public.daily_alerts
    AS PERMISSIVE FOR SELECT
    TO public
    USING (true);

-- To insert/update data, the Python pipeline uses the SERVICE_ROLE key, 
-- which automatically bypasses RLS. So no insert policy is needed for anonymous users.
